# Generated by Django 4.1.7 on 2023-03-14 18:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_grade', models.CharField(max_length=5)),
                ('subject', models.CharField(max_length=100)),
                ('descriptions', models.TextField(max_length=250)),
                ('date', models.CharField(max_length=20)),
                ('status', models.BooleanField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('until_date', models.CharField(max_length=100)),
                ('parts', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=275)),
                ('content', models.TextField(max_length=5000)),
                ('uploaded_time', models.CharField(default=datetime.datetime(2023, 3, 14, 18, 50, 48, 189987, tzinfo=datetime.timezone.utc), max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('grade', models.IntegerField(choices=[(7, 7), (8, 8), (9, 9)])),
                ('clas', models.CharField(choices=[('A', 'a'), ('B', 'b'), ('C', 'c')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_subject', models.CharField(max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=600)),
                ('status', models.BooleanField()),
                ('reply', models.TextField(max_length=1000, null=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FromUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('semester1', 'ترم اول'), ('semester1 mostamar', 'مستمر ترم اول'), ('semester1 exam', 'پایانی ترم اول'), ('semester2', 'ترم دوم'), ('semester2 mostamar', 'مستمر ترم دوم'), ('semester2 exam', 'پایانی ترم دوم')], max_length=100)),
                ('subject', models.CharField(choices=[('ریاضی', 'ریاضی'), ('علوم', 'علوم'), ('مطالعات اجتماعی', 'مطالعات اجتماعی'), ('ادبیات فارسی', 'ادبیات فارسی'), ('عربی', 'عربی'), ('قرآن', 'قرآن'), ('پیام های آسمان', 'پیام های آسمان'), ('نگارش', 'نگارش'), ('تفکر و سبک زندگی', 'تفکر و سبک زندگی'), ('ورزش', 'ورزش'), ('فرهنگ و هنر', 'فرهنگ و هنر'), ('کار و فناوری', 'کار و فناوری'), ('انگلیسی', 'انگلیسی'), ('انضباط', 'انضباط')], max_length=50)),
                ('score', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMS.student')),
            ],
        ),
        migrations.CreateModel(
            name='SampleExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('ریاضی', 'ریاضی'), ('علوم', 'علوم'), ('مطالعات اجتماعی', 'مطالعات اجتماعی'), ('ادبیات فارسی', 'ادبیات فارسی'), ('عربی', 'عربی'), ('قرآن', 'قرآن'), ('پیام های آسمان', 'پیام های آسمان'), ('نگارش', 'نگارش'), ('تفکر و سبک زندگی', 'تفکر و سبک زندگی'), ('ورزش', 'ورزش'), ('فرهنگ و هنر', 'فرهنگ و هنر'), ('کار و فناوری', 'کار و فناوری'), ('انگلیسی', 'انگلیسی')], max_length=50)),
                ('grade', models.CharField(choices=[('7', '7'), ('8', '8'), ('9', '9')], max_length=5)),
                ('file', models.FileField(upload_to='static/pdf')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMS.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('feedback', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student')], max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=600)),
                ('status', models.BooleanField()),
                ('reply', models.TextField(max_length=1000, null=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='LMS.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(choices=[('همه کاربران', 'همه کاربران'), ('همه معلمان', 'همه معلمان'), ('همه دانش آموزان', 'همه دانش آموزان')], max_length=100)),
                ('message', models.TextField(max_length=600)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_grade', models.CharField(max_length=5)),
                ('subject', models.CharField(choices=[('ریاضی', 'ریاضی'), ('علوم', 'علوم'), ('مطالعات اجتماعی', 'مطالعات اجتماعی'), ('ادبیات فارسی', 'ادبیات فارسی'), ('عربی', 'عربی'), ('قرآن', 'قرآن'), ('پیام های آسمان', 'پیام های آسمان'), ('نگارش', 'نگارش'), ('تفکر و سبک زندگی', 'تفکر و سبک زندگی'), ('ورزش', 'ورزش'), ('فرهنگ و هنر', 'فرهنگ و هنر'), ('کار و فناوری', 'کار و فناوری'), ('انگلیسی', 'انگلیسی'), ('انضباط', 'انضباط')], max_length=80)),
                ('homework', models.TextField(max_length=750)),
                ('check_date', models.DateField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMS.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='ExamScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_score', models.FloatField(null=True)),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMS.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMS.student')),
            ],
        ),
    ]
