# Generated by Django 4.1.5 on 2023-01-27 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0013_alter_user_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_grade', models.CharField(max_length=5)),
                ('subject', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=20)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('grade', models.IntegerField(choices=[(7, 7), (8, 8), (9, 9)])),
                ('clas', models.CharField(choices=[('A', 'a'), ('B', 'b'), ('C', 'c')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_subject', models.CharField(max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('semester1', 'ترم اول'), ('semester1 mostamar', 'مستمر ترم اول'), ('semester1 exam', 'پایانی ترم اول'), ('semester2', 'ترم دوم'), ('semester2 mostamar', 'مستمر ترم دوم'), ('semester2 exam', 'پایانی ترم دوم')], max_length=100)),
                ('subject', models.CharField(choices=[('ریاضی', 'ریاضی'), ('علوم', 'علوم'), ('مطالعات اجتماعی', 'مطالعات اجتماعی'), ('ادبیات فارسی', 'ادبیات فارسی'), ('عربی', 'عربی'), ('قرآن', 'قرآن'), ('پیام های آسمان', 'پیام های آسمان'), ('نگارش', 'نگارش'), ('تفکر و سبک زندگی', 'تفکر و سبک زندگی'), ('ورزش', 'ورزش'), ('فرهنگ و هنر', 'فرهنگ و هنر'), ('کار و فناوری', 'کار و فناوری'), ('انگلیسی', 'انگلیسی'), ('انضباط', 'انضباط')], max_length=50)),
                ('score', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMS.student')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student')], max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_grade', models.CharField(max_length=5)),
                ('subject', models.CharField(choices=[('ریاضی', 'ریاضی'), ('علوم', 'علوم'), ('مطالعات اجتماعی', 'مطالعات اجتماعی'), ('ادبیات فارسی', 'ادبیات فارسی'), ('عربی', 'عربی'), ('قرآن', 'قرآن'), ('پیام های آسمان', 'پیام های آسمان'), ('نگارش', 'نگارش'), ('تفکر و سبک زندگی', 'تفکر و سبک زندگی'), ('ورزش', 'ورزش'), ('فرهنگ و هنر', 'فرهنگ و هنر'), ('کار و فناوری', 'کار و فناوری'), ('انگلیسی', 'انگلیسی'), ('انضباط', 'انضباط')], max_length=80)),
                ('homework', models.TextField(max_length=750)),
                ('check_date', models.DateField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMS.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='ExamScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_score', models.FloatField()),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMS.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMS.student')),
            ],
        ),
    ]
