# Generated by Django 4.1.7 on 2023-03-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0003_festival_requests_remove_writer_author_delete_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='until_date',
            field=models.CharField(max_length=100),
        ),
    ]
