# Generated by Django 4.1.5 on 2023-01-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0003_exam_class_grade_exam_date_exam_subject_exam_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_passed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
