# Generated by Django 4.1.5 on 2023-01-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0004_exam_is_passed'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='descriptions',
            field=models.TextField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
