# Generated by Django 4.1.5 on 2023-01-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0006_rename_is_passed_exam_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examscore',
            name='exam_score',
            field=models.FloatField(null=True),
        ),
    ]
