# Generated by Django 4.1.5 on 2023-02-03 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LMS', '0008_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=600)),
                ('status', models.BooleanField()),
                ('reply', models.TextField(max_length=1000)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PublicTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(choices=[('همه کاربران', 'همه کاربران'), ('همه معلمان', 'همه معلمان'), ('همه دانش آموزان', 'همه دانش آموزان')], max_length=100)),
                ('message', models.TextField(max_length=600)),
                ('status', models.BooleanField()),
                ('reply', models.TextField(max_length=1000)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
