# Generated by Django 4.1.5 on 2023-02-03 09:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LMS', '0010_remove_publicticket_reply_remove_publicticket_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PublicTicket',
            new_name='Notification',
        ),
    ]
