# Generated by Django 4.1.5 on 2023-02-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0011_rename_publicticket_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateticket',
            name='reply',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
