# Generated by Django 4.1.5 on 2023-02-04 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0013_supportticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateticket',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='LMS.teacher'),
        ),
    ]
